// <auto-generated/>
#pragma warning disable
using LMS.Borrowing.Aggregate;
using Marten.Internal;
using Marten.Internal.Storage;
using Marten.Schema;
using Marten.Schema.Arguments;
using Npgsql;
using System;
using System.Collections.Generic;
using Weasel.Core;
using Weasel.Postgresql;

namespace Marten.Generated.DocumentStorage
{
    // START: UpsertMemberHoldRegisterOperation281785470
    public class UpsertMemberHoldRegisterOperation281785470 : Marten.Internal.Operations.StorageOperation<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>
    {
        private readonly LMS.Borrowing.Aggregate.MemberHoldRegister _document;
        private readonly System.Guid _id;
        private readonly System.Collections.Generic.Dictionary<System.Guid, System.Guid> _versions;
        private readonly Marten.Schema.DocumentMapping _mapping;
        private readonly string _tenantId;

        public UpsertMemberHoldRegisterOperation281785470(LMS.Borrowing.Aggregate.MemberHoldRegister document, System.Guid id, System.Collections.Generic.Dictionary<System.Guid, System.Guid> versions, Marten.Schema.DocumentMapping mapping, string tenantId) : base(document, id, versions, mapping)
        {
            _document = document;
            _id = id;
            _versions = versions;
            _mapping = mapping;
            _tenantId = tenantId;
        }


        public const string COMMAND_TEXT = "select public.mt_upsert_memberholdregister(?, ?, ?, ?, ?)";


        public override void Postprocess(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions)
        {
            storeVersion();
        }


        public override System.Threading.Tasks.Task PostprocessAsync(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions, System.Threading.CancellationToken token)
        {
            storeVersion();
            // Nothing
            return System.Threading.Tasks.Task.CompletedTask;
        }


        public override Marten.Internal.Operations.OperationRole Role()
        {
            return Marten.Internal.Operations.OperationRole.Upsert;
        }


        public override string CommandText()
        {
            return COMMAND_TEXT;
        }


        public override NpgsqlTypes.NpgsqlDbType DbType()
        {
            return NpgsqlTypes.NpgsqlDbType.Uuid;
        }


        public override void ConfigureParameters(Npgsql.NpgsqlParameter[] parameters, LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session)
        {
            parameters[0].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Jsonb;
            parameters[0].Value = session.Serializer.ToJson(_document);
            // .Net Class Type
            parameters[1].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar;
            parameters[1].Value = _document.GetType().FullName;
            parameters[2].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Uuid;
            parameters[2].Value = document.Id;
            setVersionParameter(parameters[3]);
            parameters[4].Value = _tenantId;
            parameters[4].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar;
        }

    }

    // END: UpsertMemberHoldRegisterOperation281785470
    
    
    // START: InsertMemberHoldRegisterOperation281785470
    public class InsertMemberHoldRegisterOperation281785470 : Marten.Internal.Operations.StorageOperation<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>
    {
        private readonly LMS.Borrowing.Aggregate.MemberHoldRegister _document;
        private readonly System.Guid _id;
        private readonly System.Collections.Generic.Dictionary<System.Guid, System.Guid> _versions;
        private readonly Marten.Schema.DocumentMapping _mapping;
        private readonly string _tenantId;

        public InsertMemberHoldRegisterOperation281785470(LMS.Borrowing.Aggregate.MemberHoldRegister document, System.Guid id, System.Collections.Generic.Dictionary<System.Guid, System.Guid> versions, Marten.Schema.DocumentMapping mapping, string tenantId) : base(document, id, versions, mapping)
        {
            _document = document;
            _id = id;
            _versions = versions;
            _mapping = mapping;
            _tenantId = tenantId;
        }


        public const string COMMAND_TEXT = "select public.mt_insert_memberholdregister(?, ?, ?, ?, ?)";


        public override void Postprocess(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions)
        {
            storeVersion();
        }


        public override System.Threading.Tasks.Task PostprocessAsync(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions, System.Threading.CancellationToken token)
        {
            storeVersion();
            // Nothing
            return System.Threading.Tasks.Task.CompletedTask;
        }


        public override Marten.Internal.Operations.OperationRole Role()
        {
            return Marten.Internal.Operations.OperationRole.Insert;
        }


        public override string CommandText()
        {
            return COMMAND_TEXT;
        }


        public override NpgsqlTypes.NpgsqlDbType DbType()
        {
            return NpgsqlTypes.NpgsqlDbType.Uuid;
        }


        public override void ConfigureParameters(Npgsql.NpgsqlParameter[] parameters, LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session)
        {
            parameters[0].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Jsonb;
            parameters[0].Value = session.Serializer.ToJson(_document);
            // .Net Class Type
            parameters[1].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar;
            parameters[1].Value = _document.GetType().FullName;
            parameters[2].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Uuid;
            parameters[2].Value = document.Id;
            setVersionParameter(parameters[3]);
            parameters[4].Value = _tenantId;
            parameters[4].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar;
        }

    }

    // END: InsertMemberHoldRegisterOperation281785470
    
    
    // START: UpdateMemberHoldRegisterOperation281785470
    public class UpdateMemberHoldRegisterOperation281785470 : Marten.Internal.Operations.StorageOperation<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>
    {
        private readonly LMS.Borrowing.Aggregate.MemberHoldRegister _document;
        private readonly System.Guid _id;
        private readonly System.Collections.Generic.Dictionary<System.Guid, System.Guid> _versions;
        private readonly Marten.Schema.DocumentMapping _mapping;
        private readonly string _tenantId;

        public UpdateMemberHoldRegisterOperation281785470(LMS.Borrowing.Aggregate.MemberHoldRegister document, System.Guid id, System.Collections.Generic.Dictionary<System.Guid, System.Guid> versions, Marten.Schema.DocumentMapping mapping, string tenantId) : base(document, id, versions, mapping)
        {
            _document = document;
            _id = id;
            _versions = versions;
            _mapping = mapping;
            _tenantId = tenantId;
        }


        public const string COMMAND_TEXT = "select public.mt_update_memberholdregister(?, ?, ?, ?, ?)";


        public override void Postprocess(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions)
        {
            storeVersion();
            postprocessUpdate(reader, exceptions);
        }


        public override async System.Threading.Tasks.Task PostprocessAsync(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions, System.Threading.CancellationToken token)
        {
            storeVersion();
            await postprocessUpdateAsync(reader, exceptions, token);
        }


        public override Marten.Internal.Operations.OperationRole Role()
        {
            return Marten.Internal.Operations.OperationRole.Update;
        }


        public override string CommandText()
        {
            return COMMAND_TEXT;
        }


        public override NpgsqlTypes.NpgsqlDbType DbType()
        {
            return NpgsqlTypes.NpgsqlDbType.Uuid;
        }


        public override void ConfigureParameters(Npgsql.NpgsqlParameter[] parameters, LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session)
        {
            parameters[0].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Jsonb;
            parameters[0].Value = session.Serializer.ToJson(_document);
            // .Net Class Type
            parameters[1].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar;
            parameters[1].Value = _document.GetType().FullName;
            parameters[2].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Uuid;
            parameters[2].Value = document.Id;
            setVersionParameter(parameters[3]);
            parameters[4].Value = _tenantId;
            parameters[4].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar;
        }

    }

    // END: UpdateMemberHoldRegisterOperation281785470
    
    
    // START: QueryOnlyMemberHoldRegisterSelector281785470
    public class QueryOnlyMemberHoldRegisterSelector281785470 : Marten.Internal.CodeGeneration.DocumentSelectorWithOnlySerializer, Marten.Linq.Selectors.ISelector<LMS.Borrowing.Aggregate.MemberHoldRegister>
    {
        private readonly Marten.Internal.IMartenSession _session;
        private readonly Marten.Schema.DocumentMapping _mapping;

        public QueryOnlyMemberHoldRegisterSelector281785470(Marten.Internal.IMartenSession session, Marten.Schema.DocumentMapping mapping) : base(session, mapping)
        {
            _session = session;
            _mapping = mapping;
        }



        public LMS.Borrowing.Aggregate.MemberHoldRegister Resolve(System.Data.Common.DbDataReader reader)
        {

            LMS.Borrowing.Aggregate.MemberHoldRegister document;
            document = _serializer.FromJson<LMS.Borrowing.Aggregate.MemberHoldRegister>(reader, 0);
            return document;
        }


        public async System.Threading.Tasks.Task<LMS.Borrowing.Aggregate.MemberHoldRegister> ResolveAsync(System.Data.Common.DbDataReader reader, System.Threading.CancellationToken token)
        {

            LMS.Borrowing.Aggregate.MemberHoldRegister document;
            document = await _serializer.FromJsonAsync<LMS.Borrowing.Aggregate.MemberHoldRegister>(reader, 0, token).ConfigureAwait(false);
            return document;
        }

    }

    // END: QueryOnlyMemberHoldRegisterSelector281785470
    
    
    // START: LightweightMemberHoldRegisterSelector281785470
    public class LightweightMemberHoldRegisterSelector281785470 : Marten.Internal.CodeGeneration.DocumentSelectorWithVersions<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>, Marten.Linq.Selectors.ISelector<LMS.Borrowing.Aggregate.MemberHoldRegister>
    {
        private readonly Marten.Internal.IMartenSession _session;
        private readonly Marten.Schema.DocumentMapping _mapping;

        public LightweightMemberHoldRegisterSelector281785470(Marten.Internal.IMartenSession session, Marten.Schema.DocumentMapping mapping) : base(session, mapping)
        {
            _session = session;
            _mapping = mapping;
        }



        public LMS.Borrowing.Aggregate.MemberHoldRegister Resolve(System.Data.Common.DbDataReader reader)
        {
            var id = reader.GetFieldValue<System.Guid>(0);

            LMS.Borrowing.Aggregate.MemberHoldRegister document;
            document = _serializer.FromJson<LMS.Borrowing.Aggregate.MemberHoldRegister>(reader, 1);
            _session.MarkAsDocumentLoaded(id, document);
            return document;
        }


        public async System.Threading.Tasks.Task<LMS.Borrowing.Aggregate.MemberHoldRegister> ResolveAsync(System.Data.Common.DbDataReader reader, System.Threading.CancellationToken token)
        {
            var id = await reader.GetFieldValueAsync<System.Guid>(0, token);

            LMS.Borrowing.Aggregate.MemberHoldRegister document;
            document = await _serializer.FromJsonAsync<LMS.Borrowing.Aggregate.MemberHoldRegister>(reader, 1, token).ConfigureAwait(false);
            _session.MarkAsDocumentLoaded(id, document);
            return document;
        }

    }

    // END: LightweightMemberHoldRegisterSelector281785470
    
    
    // START: IdentityMapMemberHoldRegisterSelector281785470
    public class IdentityMapMemberHoldRegisterSelector281785470 : Marten.Internal.CodeGeneration.DocumentSelectorWithIdentityMap<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>, Marten.Linq.Selectors.ISelector<LMS.Borrowing.Aggregate.MemberHoldRegister>
    {
        private readonly Marten.Internal.IMartenSession _session;
        private readonly Marten.Schema.DocumentMapping _mapping;

        public IdentityMapMemberHoldRegisterSelector281785470(Marten.Internal.IMartenSession session, Marten.Schema.DocumentMapping mapping) : base(session, mapping)
        {
            _session = session;
            _mapping = mapping;
        }



        public LMS.Borrowing.Aggregate.MemberHoldRegister Resolve(System.Data.Common.DbDataReader reader)
        {
            var id = reader.GetFieldValue<System.Guid>(0);
            if (_identityMap.TryGetValue(id, out var existing)) return existing;

            LMS.Borrowing.Aggregate.MemberHoldRegister document;
            document = _serializer.FromJson<LMS.Borrowing.Aggregate.MemberHoldRegister>(reader, 1);
            _session.MarkAsDocumentLoaded(id, document);
            _identityMap[id] = document;
            return document;
        }


        public async System.Threading.Tasks.Task<LMS.Borrowing.Aggregate.MemberHoldRegister> ResolveAsync(System.Data.Common.DbDataReader reader, System.Threading.CancellationToken token)
        {
            var id = await reader.GetFieldValueAsync<System.Guid>(0, token);
            if (_identityMap.TryGetValue(id, out var existing)) return existing;

            LMS.Borrowing.Aggregate.MemberHoldRegister document;
            document = await _serializer.FromJsonAsync<LMS.Borrowing.Aggregate.MemberHoldRegister>(reader, 1, token).ConfigureAwait(false);
            _session.MarkAsDocumentLoaded(id, document);
            _identityMap[id] = document;
            return document;
        }

    }

    // END: IdentityMapMemberHoldRegisterSelector281785470
    
    
    // START: DirtyTrackingMemberHoldRegisterSelector281785470
    public class DirtyTrackingMemberHoldRegisterSelector281785470 : Marten.Internal.CodeGeneration.DocumentSelectorWithDirtyChecking<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>, Marten.Linq.Selectors.ISelector<LMS.Borrowing.Aggregate.MemberHoldRegister>
    {
        private readonly Marten.Internal.IMartenSession _session;
        private readonly Marten.Schema.DocumentMapping _mapping;

        public DirtyTrackingMemberHoldRegisterSelector281785470(Marten.Internal.IMartenSession session, Marten.Schema.DocumentMapping mapping) : base(session, mapping)
        {
            _session = session;
            _mapping = mapping;
        }



        public LMS.Borrowing.Aggregate.MemberHoldRegister Resolve(System.Data.Common.DbDataReader reader)
        {
            var id = reader.GetFieldValue<System.Guid>(0);
            if (_identityMap.TryGetValue(id, out var existing)) return existing;

            LMS.Borrowing.Aggregate.MemberHoldRegister document;
            document = _serializer.FromJson<LMS.Borrowing.Aggregate.MemberHoldRegister>(reader, 1);
            _session.MarkAsDocumentLoaded(id, document);
            _identityMap[id] = document;
            StoreTracker(_session, document);
            return document;
        }


        public async System.Threading.Tasks.Task<LMS.Borrowing.Aggregate.MemberHoldRegister> ResolveAsync(System.Data.Common.DbDataReader reader, System.Threading.CancellationToken token)
        {
            var id = await reader.GetFieldValueAsync<System.Guid>(0, token);
            if (_identityMap.TryGetValue(id, out var existing)) return existing;

            LMS.Borrowing.Aggregate.MemberHoldRegister document;
            document = await _serializer.FromJsonAsync<LMS.Borrowing.Aggregate.MemberHoldRegister>(reader, 1, token).ConfigureAwait(false);
            _session.MarkAsDocumentLoaded(id, document);
            _identityMap[id] = document;
            StoreTracker(_session, document);
            return document;
        }

    }

    // END: DirtyTrackingMemberHoldRegisterSelector281785470
    
    
    // START: QueryOnlyMemberHoldRegisterDocumentStorage281785470
    public class QueryOnlyMemberHoldRegisterDocumentStorage281785470 : Marten.Internal.Storage.QueryOnlyDocumentStorage<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>
    {
        private readonly Marten.Schema.DocumentMapping _document;

        public QueryOnlyMemberHoldRegisterDocumentStorage281785470(Marten.Schema.DocumentMapping document) : base(document)
        {
            _document = document;
        }



        public override System.Guid AssignIdentity(LMS.Borrowing.Aggregate.MemberHoldRegister document, string tenantId, Marten.Storage.IMartenDatabase database)
        {
            if (document.Id == Guid.Empty) _setter(document, Marten.Schema.Identity.CombGuidIdGeneration.NewGuid());
            return document.Id;
        }


        public override Marten.Internal.Operations.IStorageOperation Update(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.UpdateMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Insert(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.InsertMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Upsert(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.UpsertMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Overwrite(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {
            throw new System.NotSupportedException();
        }


        public override System.Guid Identity(LMS.Borrowing.Aggregate.MemberHoldRegister document)
        {
            return document.Id;
        }


        public override Marten.Linq.Selectors.ISelector BuildSelector(Marten.Internal.IMartenSession session)
        {
            return new Marten.Generated.DocumentStorage.QueryOnlyMemberHoldRegisterSelector281785470(session, _document);
        }


        public override Npgsql.NpgsqlCommand BuildLoadCommand(System.Guid id, string tenant)
        {
            return new NpgsqlCommand(_loaderSql).With("id", id).With(TenantIdArgument.ArgName, tenant);
        }


        public override Npgsql.NpgsqlCommand BuildLoadManyCommand(System.Guid[] ids, string tenant)
        {
            return new NpgsqlCommand(_loadArraySql).With("ids", ids).With(TenantIdArgument.ArgName, tenant);
        }

    }

    // END: QueryOnlyMemberHoldRegisterDocumentStorage281785470
    
    
    // START: LightweightMemberHoldRegisterDocumentStorage281785470
    public class LightweightMemberHoldRegisterDocumentStorage281785470 : Marten.Internal.Storage.LightweightDocumentStorage<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>
    {
        private readonly Marten.Schema.DocumentMapping _document;

        public LightweightMemberHoldRegisterDocumentStorage281785470(Marten.Schema.DocumentMapping document) : base(document)
        {
            _document = document;
        }



        public override System.Guid AssignIdentity(LMS.Borrowing.Aggregate.MemberHoldRegister document, string tenantId, Marten.Storage.IMartenDatabase database)
        {
            if (document.Id == Guid.Empty) _setter(document, Marten.Schema.Identity.CombGuidIdGeneration.NewGuid());
            return document.Id;
        }


        public override Marten.Internal.Operations.IStorageOperation Update(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.UpdateMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Insert(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.InsertMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Upsert(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.UpsertMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Overwrite(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {
            throw new System.NotSupportedException();
        }


        public override System.Guid Identity(LMS.Borrowing.Aggregate.MemberHoldRegister document)
        {
            return document.Id;
        }


        public override Marten.Linq.Selectors.ISelector BuildSelector(Marten.Internal.IMartenSession session)
        {
            return new Marten.Generated.DocumentStorage.LightweightMemberHoldRegisterSelector281785470(session, _document);
        }


        public override Npgsql.NpgsqlCommand BuildLoadCommand(System.Guid id, string tenant)
        {
            return new NpgsqlCommand(_loaderSql).With("id", id).With(TenantIdArgument.ArgName, tenant);
        }


        public override Npgsql.NpgsqlCommand BuildLoadManyCommand(System.Guid[] ids, string tenant)
        {
            return new NpgsqlCommand(_loadArraySql).With("ids", ids).With(TenantIdArgument.ArgName, tenant);
        }

    }

    // END: LightweightMemberHoldRegisterDocumentStorage281785470
    
    
    // START: IdentityMapMemberHoldRegisterDocumentStorage281785470
    public class IdentityMapMemberHoldRegisterDocumentStorage281785470 : Marten.Internal.Storage.IdentityMapDocumentStorage<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>
    {
        private readonly Marten.Schema.DocumentMapping _document;

        public IdentityMapMemberHoldRegisterDocumentStorage281785470(Marten.Schema.DocumentMapping document) : base(document)
        {
            _document = document;
        }



        public override System.Guid AssignIdentity(LMS.Borrowing.Aggregate.MemberHoldRegister document, string tenantId, Marten.Storage.IMartenDatabase database)
        {
            if (document.Id == Guid.Empty) _setter(document, Marten.Schema.Identity.CombGuidIdGeneration.NewGuid());
            return document.Id;
        }


        public override Marten.Internal.Operations.IStorageOperation Update(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.UpdateMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Insert(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.InsertMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Upsert(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.UpsertMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Overwrite(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {
            throw new System.NotSupportedException();
        }


        public override System.Guid Identity(LMS.Borrowing.Aggregate.MemberHoldRegister document)
        {
            return document.Id;
        }


        public override Marten.Linq.Selectors.ISelector BuildSelector(Marten.Internal.IMartenSession session)
        {
            return new Marten.Generated.DocumentStorage.IdentityMapMemberHoldRegisterSelector281785470(session, _document);
        }


        public override Npgsql.NpgsqlCommand BuildLoadCommand(System.Guid id, string tenant)
        {
            return new NpgsqlCommand(_loaderSql).With("id", id).With(TenantIdArgument.ArgName, tenant);
        }


        public override Npgsql.NpgsqlCommand BuildLoadManyCommand(System.Guid[] ids, string tenant)
        {
            return new NpgsqlCommand(_loadArraySql).With("ids", ids).With(TenantIdArgument.ArgName, tenant);
        }

    }

    // END: IdentityMapMemberHoldRegisterDocumentStorage281785470
    
    
    // START: DirtyTrackingMemberHoldRegisterDocumentStorage281785470
    public class DirtyTrackingMemberHoldRegisterDocumentStorage281785470 : Marten.Internal.Storage.DirtyCheckedDocumentStorage<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>
    {
        private readonly Marten.Schema.DocumentMapping _document;

        public DirtyTrackingMemberHoldRegisterDocumentStorage281785470(Marten.Schema.DocumentMapping document) : base(document)
        {
            _document = document;
        }



        public override System.Guid AssignIdentity(LMS.Borrowing.Aggregate.MemberHoldRegister document, string tenantId, Marten.Storage.IMartenDatabase database)
        {
            if (document.Id == Guid.Empty) _setter(document, Marten.Schema.Identity.CombGuidIdGeneration.NewGuid());
            return document.Id;
        }


        public override Marten.Internal.Operations.IStorageOperation Update(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.UpdateMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Insert(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.InsertMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Upsert(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {

            return new Marten.Generated.DocumentStorage.UpsertMemberHoldRegisterOperation281785470
            (
                document, Identity(document),
                session.Versions.ForType<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>(),
                _document
                , tenant
            );
        }


        public override Marten.Internal.Operations.IStorageOperation Overwrite(LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Internal.IMartenSession session, string tenant)
        {
            throw new System.NotSupportedException();
        }


        public override System.Guid Identity(LMS.Borrowing.Aggregate.MemberHoldRegister document)
        {
            return document.Id;
        }


        public override Marten.Linq.Selectors.ISelector BuildSelector(Marten.Internal.IMartenSession session)
        {
            return new Marten.Generated.DocumentStorage.DirtyTrackingMemberHoldRegisterSelector281785470(session, _document);
        }


        public override Npgsql.NpgsqlCommand BuildLoadCommand(System.Guid id, string tenant)
        {
            return new NpgsqlCommand(_loaderSql).With("id", id).With(TenantIdArgument.ArgName, tenant);
        }


        public override Npgsql.NpgsqlCommand BuildLoadManyCommand(System.Guid[] ids, string tenant)
        {
            return new NpgsqlCommand(_loadArraySql).With("ids", ids).With(TenantIdArgument.ArgName, tenant);
        }

    }

    // END: DirtyTrackingMemberHoldRegisterDocumentStorage281785470
    
    
    // START: MemberHoldRegisterBulkLoader281785470
    public class MemberHoldRegisterBulkLoader281785470 : Marten.Internal.CodeGeneration.BulkLoader<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid>
    {
        private readonly Marten.Internal.Storage.IDocumentStorage<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid> _storage;

        public MemberHoldRegisterBulkLoader281785470(Marten.Internal.Storage.IDocumentStorage<LMS.Borrowing.Aggregate.MemberHoldRegister, System.Guid> storage) : base(storage)
        {
            _storage = storage;
        }


        public const string MAIN_LOADER_SQL = "COPY public.mt_doc_memberholdregister(\"mt_dotnet_type\", \"id\", \"mt_version\", \"tenant_id\", \"data\") FROM STDIN BINARY";

        public const string TEMP_LOADER_SQL = "COPY mt_doc_memberholdregister_temp(\"mt_dotnet_type\", \"id\", \"mt_version\", \"tenant_id\", \"data\") FROM STDIN BINARY";

        public const string COPY_NEW_DOCUMENTS_SQL = "insert into public.mt_doc_memberholdregister (\"id\", \"tenant_id\", \"data\", \"mt_version\", \"mt_dotnet_type\", mt_last_modified) (select mt_doc_memberholdregister_temp.\"id\", mt_doc_memberholdregister_temp.\"tenant_id\", mt_doc_memberholdregister_temp.\"data\", mt_doc_memberholdregister_temp.\"mt_version\", mt_doc_memberholdregister_temp.\"mt_dotnet_type\", transaction_timestamp() from mt_doc_memberholdregister_temp left join public.mt_doc_memberholdregister on mt_doc_memberholdregister_temp.id = public.mt_doc_memberholdregister.id where public.mt_doc_memberholdregister.id is null)";

        public const string OVERWRITE_SQL = "update public.mt_doc_memberholdregister target SET tenant_id = source.tenant_id, data = source.data, mt_version = source.mt_version, mt_dotnet_type = source.mt_dotnet_type, mt_last_modified = transaction_timestamp() FROM mt_doc_memberholdregister_temp source WHERE source.id = target.id";

        public const string CREATE_TEMP_TABLE_FOR_COPYING_SQL = "create temporary table mt_doc_memberholdregister_temp as select * from public.mt_doc_memberholdregister limit 0";


        public override string CreateTempTableForCopying()
        {
            return CREATE_TEMP_TABLE_FOR_COPYING_SQL;
        }


        public override string CopyNewDocumentsFromTempTable()
        {
            return COPY_NEW_DOCUMENTS_SQL;
        }


        public override string OverwriteDuplicatesFromTempTable()
        {
            return OVERWRITE_SQL;
        }


        public override void LoadRow(Npgsql.NpgsqlBinaryImporter writer, LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Storage.Tenant tenant, Marten.ISerializer serializer)
        {
            writer.Write(document.GetType().FullName, NpgsqlTypes.NpgsqlDbType.Varchar);
            writer.Write(document.Id, NpgsqlTypes.NpgsqlDbType.Uuid);
            writer.Write(Marten.Schema.Identity.CombGuidIdGeneration.NewGuid(), NpgsqlTypes.NpgsqlDbType.Uuid);
            writer.Write(tenant.TenantId, NpgsqlTypes.NpgsqlDbType.Varchar);
            writer.Write(serializer.ToJson(document), NpgsqlTypes.NpgsqlDbType.Jsonb);
        }


        public override async System.Threading.Tasks.Task LoadRowAsync(Npgsql.NpgsqlBinaryImporter writer, LMS.Borrowing.Aggregate.MemberHoldRegister document, Marten.Storage.Tenant tenant, Marten.ISerializer serializer, System.Threading.CancellationToken cancellation)
        {
            await writer.WriteAsync(document.GetType().FullName, NpgsqlTypes.NpgsqlDbType.Varchar, cancellation);
            await writer.WriteAsync(document.Id, NpgsqlTypes.NpgsqlDbType.Uuid, cancellation);
            await writer.WriteAsync(Marten.Schema.Identity.CombGuidIdGeneration.NewGuid(), NpgsqlTypes.NpgsqlDbType.Uuid, cancellation);
            await writer.WriteAsync(tenant.TenantId, NpgsqlTypes.NpgsqlDbType.Varchar, cancellation);
            await writer.WriteAsync(serializer.ToJson(document), NpgsqlTypes.NpgsqlDbType.Jsonb, cancellation);
        }


        public override string MainLoaderSql()
        {
            return MAIN_LOADER_SQL;
        }


        public override string TempLoaderSql()
        {
            return TEMP_LOADER_SQL;
        }

    }

    // END: MemberHoldRegisterBulkLoader281785470
    
    
    // START: MemberHoldRegisterProvider281785470
    public class MemberHoldRegisterProvider281785470 : Marten.Internal.Storage.DocumentProvider<LMS.Borrowing.Aggregate.MemberHoldRegister>
    {
        private readonly Marten.Schema.DocumentMapping _mapping;

        public MemberHoldRegisterProvider281785470(Marten.Schema.DocumentMapping mapping) : base(new MemberHoldRegisterBulkLoader281785470(new QueryOnlyMemberHoldRegisterDocumentStorage281785470(mapping)), new QueryOnlyMemberHoldRegisterDocumentStorage281785470(mapping), new LightweightMemberHoldRegisterDocumentStorage281785470(mapping), new IdentityMapMemberHoldRegisterDocumentStorage281785470(mapping), new DirtyTrackingMemberHoldRegisterDocumentStorage281785470(mapping))
        {
            _mapping = mapping;
        }


    }

    // END: MemberHoldRegisterProvider281785470
    
    
}

